package com.example.demo.model;

import jakarta.persistence.*;

// This class represents a user entity mapped to the database
@Entity
@Table(name = "users")
public class User {

    // ID is the primary key and is auto-generated by the database
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Unique username for the user
    @Column(nullable = false, unique = true)
    private String username;

    // User's email address
    @Column(nullable = false, unique = true)
    private String email;

    // User's password
    @Column(nullable = false)
    private String password;

    // User's first name
    @Column(nullable = false)
    private String firstName;

    // User's last name
    @Column(nullable = false)
    private String lastName;

    // Getters and setters for all fields

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}
