POST https://project2db-b60469abc86b.herokuapp.com/api/auth/register
Content-Type: application/json

{
  "username": "DaGoat",
  "password": "LeBron1",
  "email": "LeBron@example.com",
  "firstName": "Lebron",
  "lastName": "James"
}